merges:
  - action: delete_branch
labels:
  "bot: duplicate":
    action: close
    delay: 15 minutes
  "bot: merge when passing": merge
  "status: needs reproduction":
    action: close
    delay: 7 days
    comment: >-
      Hello!

      Sorry to hear that you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to [create a minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

      _Note: if a reproduction has not been supplied in 7 days, this issue will be closed by me, Ranger bot 🤠🤖._

      Once you've supplied a reproduction remove the `status: needs reproduction` label, and this issue will remain open and we can take a closer look!

      Thanks for using Gatsby! 💜
comments:
  - action: label
    # either a string or a string representation of a regular expresssion
    pattern: /duplicate of/i
    labels:
      - "bot: duplicate"
  - action: label
    pattern: /needs reproduction/i
    labels:
      - "status: needs reproduction"
