merges:
  - action: delete_branch

labels:
  "bot: duplicate":
    action: close
    delay: 15 minutes

comments:
  - action: label
    pattern: /duplicate of \#?[\d]+/i
    labels:
      - "bot: duplicate"

commits:
  - action: label
    pattern: /merge when passing/i
    labels: 
      - "bot: merge when passing"
